# Generated by Django 6.0 on 2026-01-06 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='public_key',
        ),
    ]
