# Generated by Django 6.0 on 2026-01-06 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signalidentity',
            old_name='identity_key_public',
            new_name='public_key',
        ),
    ]
