# Generated by Django 6.0 on 2026-01-08 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0003_signalprekeyrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signalmessage',
            name='receiver',
        ),
    ]
