# Generated by Django 6.0 on 2026-01-09 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0004_remove_signalmessage_receiver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signalmessage',
            name='sender',
        ),
    ]
