# Generated by Django 6.0 on 2026-01-10 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0005_remove_signalmessage_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signalmessage',
            name='ciphertext',
            field=models.TextField(),
        ),
    ]
