# Generated by Django 6.0 on 2026-01-15 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0007_signalidentity_registration_id_signalkyberprekey'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SignalKyberPreKey',
        ),
    ]
