# Generated by Django 6.0 on 2026-01-15 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0008_delete_signalkyberprekey'),
    ]

    operations = [
        migrations.AddField(
            model_name='signalmessage',
            name='signal_type',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
