# Generated by Django 6.0 on 2026-01-15 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0009_signalmessage_signal_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signalmessage',
            name='ciphertext',
            field=models.BinaryField(),
        ),
    ]
