# Generated by Django 6.0 on 2026-01-16 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0010_alter_signalmessage_ciphertext'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='signalprekeyrequest',
            unique_together=set(),
        ),
    ]
